### ISSUE TITLE
Symfony 3 problem

### ISSUE THREAD

**Issue by nietonchique** [waylaidwanderer/PHP-SteamCommunity#4]
```
[RuntimeException]                                                          
  The autoloader expected class "waylaidwanderer\SteamCommunity\TradeOffers"  
   to be defined in file "/servers/www/dev.a-vd.pro/vendor/waylaidwanderer/p  
  hp-steamcommunity/TradeOffers.php". The file was found but the class was n  
  ot in it, the class name or namespace probably has a typo.
```

I use symfony 3

**Comment by waylaidwanderer** [comment]
This is most likely an issue with your Symfony config. Try googling "The autoloader expected class to be defined in file" or "The file was found but the class was not in it, the class name or namespace probably has a typo.".

I've used this library myself in a project by installing it via Composer with no issues.

**Comment by nietonchique** [comment]
I cant find solution... 
I googled this problem. It is recommended to change the examples of your project (my bad in english)

**Comment by waylaidwanderer** [comment]
What does your config.yml look like?

**Comment by nietonchique** [comment]
config.yml

``` yml
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru

framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        unix_socket: /var/run/mysqld/mysqld.sock

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

```

parameters.yml 

``` yml
parameters:
    database_host: XXX
    database_port: null
    database_name: XXX
    database_user: XXX
    database_password: XXX
    mailer_transport: smtp
    mailer_host: XXX
    mailer_user: null
    mailer_password: null
    secret: XXXX
```

routing.yml

``` yml
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
```

services.yml

``` yml
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
```
